server:
  port: 7969
spring:
  application:
    name: leaf_manager

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8989/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    leaf_user:
      path: /user/**
      serviceId: leaf_user
